# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  containers:
  - container: rust_build
    image: rust:1.30.0-stretch

container: my_container

steps:
- script: make build
